version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - pip install esp_docs
    - pwd
    - echo $PATH
    - cd docs && pwd && build-docs -l en -bs html
    - mkdir -p _readthedocs
    - cp -Rv docs/_build/en/generic/html _readthedocs
#   jobs:
#     pre_build:
#       - doxygen docs/Doxyfile

# # Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/en/conf.py

# # Declare the Python requirements to build the docs
# python:
#   install:
#   - requirements: docs/requirements.txt
