#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := lcd_example

EXTRA_COMPONENT_DIRS := ../../

include $(IDF_PATH)/make/project.mk
